
 hosts: Dev 
 tasks: 
 name: Install Apache web server
 apt:  pkg=apache state=installed update_cache=true 

 hosts: Prod
 tasks:
 name: Install Apache web server
 apt: pkg=apache state=installed update_cache=true

        
