---
- hosts: all 
  become: true


  tasks:
  - name: Set hostname
    hostname:
      name:   "{{inventory_hostname}}"

  - name: install httpd
    yum: 
      name:   httpd 
      state:  present
    when:   '"webmachines" in group_names'

  - name: start and enable webservers
    service: 
      name: httpd
      state: started
      enabled: true
    when:   '"webmachines" in group_names'

  - openssh_keypair:
      path: /home/ec2-user/.ssh/id_rsa.pub
    when: inventory_hostname == 'jump'

  
  - name: Fetching file to install ssh keys
    fetch:
      src: /home/ec2-user/.ssh/id_rsa.pub
      dest: /tmp/id_rsa.pub
 
  - name: Set authorized key taken from file
    authorized_key:
      user: nbrown
      state: present
      key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
