---
- hosts: all 
  become: true


  tasks:
  - name: Set hostname
    hostname:
      name:   "{{inventory_hostname}}"

  - name: install httpd
    yum: 
      name:   httpd 
      state:  present
    when:   '"webmachines" in group_names'

  - name: start and enable webservers
    service: 
      name: httpd
      state: started
      enabled: true
    when:   '"webmachines" in group_names'

  - openssh_keypair:
      path: /tmp/id_ssh_rsa
    when: inventory_hostname == 'jump'

  
  - name: Fetching file to install ssh keys
    fetch:
      src: /etc/ssh/ssh_host_rsa_key.pub
      dest: /tmp/fetched
 
  - name: Copy the file from jump to local hosts
    copy: src=/etc/ssh/ssh_host_rsa_key.pub dest=/tmp/fetched
    when: "[ inventory_hostname == 'local' ]" 


